name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your desired Python version
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 *.py
    - name: Run unit tests
      run: |
        python -m unittest discover --verbose --failfast